### ISSUE TITLE
1.16

### ISSUE THREAD

**Issue by AlbeMiglio** [egold555/CorpseReborn#112]
Sending in the attached comment below the error thrown, paper 1.16.5

**Comment by AlbeMiglio** [comment]
`[21:12:25] [Server thread/WARN]: java.lang.NoSuchFieldException: modifiers
[21:12:25] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2489)
[21:12:25] [Server thread/WARN]: 	at org.golde.bukkit.corpsereborn.nms.nmsclasses.NMSCorpses_v1_16_R3.getNextEntityIdAtomic(NMSCorpses_v1_16_R3.java:244)
[21:12:25] [Server thread/WARN]: 	at org.golde.bukkit.corpsereborn.nms.nmsclasses.NMSCorpses_v1_16_R3.getNextEntityId(NMSCorpses_v1_16_R3.java:234)
[21:12:25] [Server thread/WARN]: 	at org.golde.bukkit.corpsereborn.nms.nmsclasses.NMSCorpses_v1_16_R3.spawnCorpse(NMSCorpses_v1_16_R3.java:131)
[21:12:25] [Server thread/WARN]: 	at org.golde.bukkit.corpsereborn.listeners.PlayerDeath.onPlayerDeath(PlayerDeath.java:34)
[21:12:25] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor386.execute(Unknown Source)
[21:12:25] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[21:12:25] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[21:12:25] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:12:25] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[21:12:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:867)
[21:12:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityPlayer.die(EntityPlayer.java:1000)
[21:12:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:133)
[21:12:25] [Server thread/WARN]: 	at com.Zrips.CMI.commands.list.suicide.perform(suicide.java:88)
[21:12:25] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:385)
[21:12:25] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[21:12:25] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[21:12:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810)
[21:12:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2286)
[21:12:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2101)
[21:12:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2054)
[21:12:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50)
[21:12:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8)
[21:12:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55)
[21:12:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[21:12:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[21:12:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[21:12:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[21:12:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1326)
[21:12:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1319)
[21:12:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[21:12:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1295)
[21:12:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139)
[21:12:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[21:12:25] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
`

**Comment by K4zoku** [comment]
Change java version to 11 or 8
