### ISSUE TITLE
Worldguard broken again?

### ISSUE THREAD

**Issue by egold555** [egold555/CorpseReborn#35]
om.sk89q.worldguard.bukkit.WorldGuardPlugin.getFlagRegistry()Lcom/sk89q/worldguard/protection/flags/registry/FlagRegistry; initializing CorpseReborn v2.12.1 (Is it up to date?)
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getFlagRegistry()Lcom/sk89q/worldguard/protection/flags/registry/FlagRegistry;
    at org.golde.bukkit.corpsereborn.listeners.WorldguardListener.<init>(WorldguardListener.java:25) ~[?:?]
    at org.golde.bukkit.corpsereborn.Main.onLoad(Main.java:64) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297) [murder.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [murder.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [murder.jar:git-Spigot-21fe707-e1ebe52]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

-- Spigot josecuervo2016

**Comment by egold555** [comment]
Worldguard 6.2 needed minimum
