### ISSUE TITLE
Error on 1.13 WorldGuard

### ISSUE THREAD

**Issue by xCraftRayX** [egold555/CorpseReborn#73]
I use WorldGuard 7.0.0-SNAPSHOT
When plugin was loaded:
`[17:07:27] [Server thread/INFO]: [CorpseReborn] Loading CorpseReborn v2.13.3
[17:07:27] [Server thread/INFO]: [CorpseReborn] Worldguard detected. Adding custom spawn flags
[17:07:27] [Server thread/ERROR]: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getFlagRegistry()Lcom/sk89q/worldguard/protection/flags/registry/FlagRegistry; initializing CorpseReborn v2.13.3 (Is it up to date?)
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getFlagRegistry()Lcom/sk89q/worldguard/protection/flags/registry/FlagRegistry;
	at org.golde.bukkit.corpsereborn.listeners.WorldguardListener.<init>(WorldguardListener.java:31) ~[?:?]
	at org.golde.bukkit.corpsereborn.Main.onLoad(Main.java:64) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:325) [spigot.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [spigot.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot.jar:git-Spigot-f6a273b-a639ae4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`

**Comment by egold555** [comment]
Need to find time to test this, but thanks for reporting.
