### ISSUE TITLE
java.lang.IllegalAccessException when using API to spawn corpse

### ISSUE THREAD

**Issue by dilanx** [egold555/CorpseReborn#98]
Whenever I use the CorpseAPI#spawnCorpse() method, I get this:

> java.lang.IllegalAccessException: Can not set static final java.util.concurrent.atomic.AtomicInteger field net.minecraft.server.v1_14_R1.Entity.entityCount to java.util.concurrent.atomic.AtomicInteger
12.07 21:51:06 [Server] Server thread/WARN at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
12.07 21:51:06 [Server] Server thread/WARN at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
12.07 21:51:06 [Server] Server thread/WARN at sun.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:77)
12.07 21:51:06 [Server] Server thread/WARN at java.lang.reflect.Field.set(Field.java:764)
12.07 21:51:06 [Server] Server thread/WARN at org.golde.bukkit.corpsereborn.nms.nmsclasses.NMSCorpses_v1_14_R1.getNextEntityIdAtomic(NMSCorpses_v1_14_R1.java:258)
12.07 21:51:06 [Server] Server thread/WARN at org.golde.bukkit.corpsereborn.nms.nmsclasses.NMSCorpses_v1_14_R1.getNextEntityId(NMSCorpses_v1_14_R1.java:242)
12.07 21:51:06 [Server] Server thread/WARN at org.golde.bukkit.corpsereborn.nms.nmsclasses.NMSCorpses_v1_14_R1.spawnCorpse(NMSCorpses_v1_14_R1.java:133)
12.07 21:51:06 [Server] Server thread/WARN at org.golde.bukkit.corpsereborn.CorpseAPI.CorpseAPI.spawnCorpse(CorpseAPI.java:48)
12.07 21:51:06 [Server] Server thread/WARN at org.golde.bukkit.corpsereborn.CorpseAPI.CorpseAPI.spawnCorpse(CorpseAPI.java:75)
12.07 21:51:06 [Server] Server thread/WARN at org.golde.bukkit.corpsereborn.CorpseAPI.CorpseAPI.spawnCorpse(CorpseAPI.java:148)
12.07 21:51:06 [Server] Server thread/WARN at com.blockhead7360.ps.plugin.DetectivePluginEventListener.onPlayerDeath(DetectivePluginEventListener.java:149)
12.07 21:51:06 [Server] Server thread/WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12.07 21:51:06 [Server] Server thread/WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12.07 21:51:06 [Server] Server thread/WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12.07 21:51:06 [Server] Server thread/WARN at java.lang.reflect.Method.invoke(Method.java:498)
12.07 21:51:06 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)
12.07 21:51:06 [Server] Server thread/WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
12.07 21:51:06 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529)
12.07 21:51:06 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514)
12.07 21:51:06 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:734)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.EntityPlayer.die(EntityPlayer.java:519)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1169)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.EntityHuman.damageEntity(EntityHuman.java:770)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.EntityPlayer.damageEntity(EntityPlayer.java:674)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.EntityHuman.attack(EntityHuman.java:1019)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.EntityPlayer.attack(EntityPlayer.java:1542)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1864)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(SourceFile:69)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(SourceFile:13)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886)
12.07 21:51:06 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819)
12.07 21:51:06 [Server] Server thread/WARN at java.lang.Thread.run(Thread.java:748)

How do I solve this issue? It doesn't seem to be affecting anything in the game, so even just a way to prevent this from appearing in the console.

**Comment by egold555** [comment]
Intresting. Can you do "/cr dump" and send me the link?

**Comment by dilanx** [comment]
https://pastebin.com/Xhc1mQXc

I am using a version of Minecraft that isn't compatible with CorpseReborn (1.14.4). Could that be the issue?
